version: '3.8'

services:
  dev-db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jonathan06
      POSTGRES_DB: appointment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
