version: '3.8'

services:
  dev-db:
    image: mongo:6
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jonathan06
      MONGO_INITDB_DATABASE: firstP
